vich_uploader:
    db_driver: orm
    metadata: 
        type: attribute

    mappings:
       recipe_images:
           uri_prefix: /imagesLivres
           upload_destination: '%kernel.project_dir%/public/imagesLivres'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
